name: Build Auto-Deco-Kuzureta-Style

on:
push:
pull_request:
workflow_dispatch:

jobs:
build:
strategy:
fail-fast: false
matrix:
platform:
- win
- android32
- android64
- macos
- ios

runs-on: ubuntu-latest

steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Build Geode Mod
    uses: geode-sdk/build-geode-mod@v2
    with:
      target: ${{ matrix.platform }}
